# Generated by Django 5.0.3 on 2024-04-02 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salary_package', models.IntegerField()),
                ('last_date_of_registration', models.DateField()),
                ('eligibility', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('job_type', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('batchCanApply', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.company')),
            ],
        ),
        migrations.CreateModel(
            name='PassedOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('salary_package', models.IntegerField()),
                ('last_date_of_registration', models.DateField()),
                ('eligibility', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('job_type', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.company')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=50)),
                ('placed', models.BooleanField(default=False)),
                ('interested', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.department')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.drive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.student')),
            ],
        ),
    ]
